#!/bin/bash
#Calculates covariance 
if [[ ("$1" == "-h" ) || ( "$1" == "--help" ) ]]; then
echo "This programs takes one input file with two columns then computes the covariance"
echo " "
echo "Example: "
echo ">> ./covar list1"
echo ">> 2.57143"
echo " "
echo "Copyright: "
echo "Jin Hyun Cheong 2015"
echo "jin.hyun.cheong.gr@dartmouth.edu"
echo "Psychological Brain Sciences"
echo "Dartmouth College"
exit 0
else
awk '{ 	
	x[NR]=$1;
	y[NR]=$2;
}
END {
for (i in x) {
sum_x += x[i]
sum_y += y[i]
}
m_x = sum_x / FNR
m_y = sum_y / FNR
for (i in x) {
sum_dxdy += (x[i]-m_x)*(y[i]-m_y)
}
print sum_dxdy / FNR
 }' $1 $2

fi

