#!/bin/bash
#Calculates variance
if [[ ("$1" == "-h" ) || ( "$1" == "--help" ) ]]; then
echo "This programs takes one input file with one column then computes the variance"
echo " "
echo "Example: "
echo ">> ./mean list2"
echo ">> 47.8222"
echo " "
echo "Copyright: "
echo "Jin Hyun Cheong 2015"
echo "jin.hyun.cheong.gr@dartmouth.edu"
echo "Psychological Brain Sciences"
echo "Dartmouth College"
exit 0
else
var=$1
awk '{
x[NR] = $1;
sum += $1;
}
END {
for (i in x) {
	sumsq += (x[i]-(sum/NR))**2
}
print sumsq/NR }' $var
fi
