#!/bin/bash
#Calculates covariance 
if [ "$1" == "-h" ] ; then
echo "This programs takes an input file with two columns then compute the covariance"
exit 0
else
awk '{ 	
	x[NR]=$1;
	y[NR]=$2;
}
END {
for (i in x) {
sum_x += x[i]
sum_y += y[i]
}
m_x = sum_x / FNR
m_y = sum_y / FNR
for (i in x) {
sum_dxdy += (x[i]-m_x)*(y[i]-m_y)
}
print sum_dxdy / FNR
 }' $1 $2

fi

